backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "charts"
    label: "Charts"
    folder: "content/charts"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Chart Image", name: "image", widget: "image"}
      - {label: "Alternate description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

